server:
  port: 8080

spring:
  application:
    name: NEUSoftPractice
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://localhost:3306/neusoftpractice?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: 50MB
      max-request-size: 50MB
      location: /tmp/upload
  data:
    redis:
      host: localhost
      port: 6379
      database: 0

springdoc:
  api-docs:
    enabled: true
    path: /user-services/v3/api-docs
  swagger-ui:
    enabled: true
    path: /user-services/swagger-ui.html


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID